### ISSUE TITLE
Can only run 1 test once per neovim load

### ISSUE THREAD

**Issue by nexxai** [V13Axel/neotest-pest#11]
I'm not sure what has happened aside from just doing my usual plugin updating in lazy.nvim, but now all of a sudden, my keymap for neotest will run once (and it will seemingly run successfully, adding the green check to the gutter), and then not again until I restart neovim.

I cannot think of any reason why that might be case, but I'm happy to provide any other data to help troubleshoot it.

I've run `:checkhealth` and nothing seems to be out of the ordinary.

**Comment by nexxai** [comment]
This can be ignored.  I don't know if something changed in the default LazyVim config but after defining the specific `<leader>t` keymap in the plugin's initial config, I was able to overwrite the default behavior which literally does nothing.

<img width="441" alt="Screenshot 2024-06-10 at 1 55 15 PM" src="https://github.com/V13Axel/neotest-pest/assets/4316564/b25b40be-3ccf-4760-a062-e94fb536f8fd">

Anyways, I'm all good now.

**Comment by V13Axel** [comment]
Definitely sounds strange! Glad you were able to sort it out.
